name: coding-style

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:

env: 
  MIRROR_URL: "git@github.com:EpitechPromo2028/B-DOP-200-COT-2-1-chocolatine-amour.guidi.git"
  EXECUTABLES: "minicut"

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - uses: actions/checkout@v4
      - id: check_coding_style
        run: check.sh $(pwd) $(pwd)
  
  check_program_compilation:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v4
      - name: it_make
        id: check_program_compilation
        run: make
        timeout-minutes: 2
      - name: it_make_clean
        id: check_program_compilation
        run: make clean
        
        
