name: coding-style

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env: 
  - MIRROR_URL: "git@github.com:EpitechPromo2028/B-DOP-200-COT-2-1-chocolatine-amour.guidi.git"
  - EXECUTABLES: "minicut"

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - run: check.sh $(pwd) $(pwd)
