name: mirror

on: [push]

jobs: 
  mirror_job:
    runs-on: ubuntu-latest
    steps:
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2028/B-CPE-110-COT-1-1-bssecured-amour.guidi.git
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
